name: AppImage Continuous

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  linux-appimage-continuous-build:
    name: Linux ${{ matrix.os.arch }} (Continuous build)
    runs-on: ${{ matrix.os.label }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: "Dolphin build"
            arch: x86_64
          - runs-on: ubuntu-24.04-arm
            name: "Dolphin build"
            arch: aarch64
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
    - uses: actions/checkout@v4

    - uses: abbbi/github-actions-tune@v1

    - name: Build libcpuid
      run: bash -x ./scripts/build_libcpuid.sh "$BUILD_TYPE"

    - name: Build CPU-X
      run: bash -x ./scripts/build_cpu_x.sh "$BUILD_TYPE" "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE/AppDir"

    - name: Package CPU-X as an AppImage
      run: |
        bash -x ./scripts/build_appimage.sh "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE/AppDir"
        ls -l AppImage/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-${{ matrix.os.arch }}
        path: AppImage/CPU-X-*


  linux-appimage-continuous-release:
    name: Linux (Continuous release)
    needs: linux-appimage-continuous-build
    runs-on: ubuntu-latest

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: AppImage/
        merge-multiple: true

    - name: Display structure of downloaded files
      run: ls -R AppImage/

    - name: Delete previous continuous release
      uses: dev-drprasad/delete-tag-and-release@v1.1
      with:
        tag_name: continuous
        delete_release: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create continuous release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "AppImage/CPU-X-*.AppImage*"
        body: |
          :heavy_check_mark:CPU-X AppImage built from latest commit ([${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})). See [known issues](https://github.com/TheTumultuousUnicornOfDarkness/CPU-X/wiki/appimage).
        commit: ${{ github.sha }}
        draft: false
        name: Continuous build
        prerelease: true
        removeArtifacts: true
        replacesArtifacts: true
        skipIfReleaseExists: false
        tag: continuous
        token: "${{ secrets.GITHUB_TOKEN }}"
